### Задание 1.1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.



In [1]:
import numpy as np

##### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
a = np.arange(12,24)

In [3]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


###### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [4]:
a1 = a.reshape(3,4)

In [5]:
a1


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a2  = a.reshape(2,6)

In [7]:
a2


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
np.reshape(a,(4,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
np.reshape(a,(6,2))


array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a5 = a.reshape(12,1)

In [11]:
a5


array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

##### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [12]:
b1 = a.reshape(-1,4)
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
np.reshape(a,(-1,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
np.reshape(a,(-1,6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
np.reshape(a,(4,-1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [16]:
np.reshape(a,(-1,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Да, можно, т.к. данный массив является вектором

### Задание 1.2

###### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. ????


In [17]:
c = np.random.randn(3,4)
c

array([[-1.26120407, -1.13323394,  0.18971258,  0.75385155],
       [-1.08933127, -1.53717231,  1.56990288, -0.06335144],
       [-0.14743635,  1.56657146,  1.3593138 ,  0.28890123]])

In [18]:
c1 =np.random.randn(3,4)
c1


array([[-0.27554202, -0.5070624 , -0.4276551 , -0.67976802],
       [-0.91718261,  0.42827174, -0.79483876,  1.34991893],
       [-0.05721483,  0.22693501,  2.63713857,  0.12614434]])

In [19]:
c1.size

12

In [20]:
c1 = c1.flatten()
c1

array([-0.27554202, -0.5070624 , -0.4276551 , -0.67976802, -0.91718261,
        0.42827174, -0.79483876,  1.34991893, -0.05721483,  0.22693501,
        2.63713857,  0.12614434])

In [21]:
c1.size

12

### Задание 1.3 


### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 

In [22]:
d = np.arange(20,0,-2)
d

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 


In [23]:
d1 = np.arange(20,1,-2).reshape(1,10)
d1

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

### В чем разница между массивами a и b?



In [24]:
d.shape

(10,)

In [25]:
d1.shape


(1, 10)

In [26]:
d.size

10

In [27]:
d.size

10

In [28]:
d == d1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [29]:
d.ndim



1

In [30]:
d1.ndim

2

Различия в колличестве измерений

### Задание 1.4

### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [31]:
for i in range(2,10):
    for j in range(5):
        e = np.zeros((i,j))
        e1 = np.ones((i+1,j))
        v = np.vstack((e,e1))
        if v.size == 10:
            break
    if v.size ==10:
        break
print(e.size,e1.size,v.size)
print(e.shape,e1.shape,v.shape)

4 6 10
(2, 2) (3, 2) (5, 2)


### Задание 1.5

### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.




In [32]:
f = np.arange(0,12)

### Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.


In [33]:
A = f.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Получить матрицу At путем транспонирования матрицы A.


In [34]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

### Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.


In [35]:
A.shape[0] == At.shape[1] 

True

In [36]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

### Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [37]:
B.shape

(4, 4)

In [38]:
np.linalg.det(B)

0.0

In [39]:
B_inv = np.linalg.inv(B)

LinAlgError: Singular matrix

### Квадратная матрица обратима, только когда ее определитель не равен 0

### Задание 1.6

### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.



In [40]:
np.random.seed(42)

### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [41]:
g = np.random.randint(0,16,16)
g

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Поменяйте его форму так, чтобы получилась квадратная матрица C. 


In [42]:
C = g.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

### Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.


In [43]:
D = np.add(B,(np.dot(C,10)))
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

### Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [44]:
np.linalg.det(D)

-28511999.999999944

In [45]:
np.linalg.matrix_rank(D)

4

In [46]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 



In [47]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

### С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C


In [48]:
E = np.where([D_inv],B,C)
E


array([[[  5,  14,  23,  14],
        [ 10,   7,  12, 122],
        [  6,   9,   2, 212],
        [ 32,  10, 212,   4]]])